# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"
        # Ignore non-LTS Django releases
        # https://www.djangoproject.com/download/#supported-versions
        versions:
          - ">=4.3,<5.2"
    target-branch: "develop"
    groups:
      dependencies:
        patterns:
          - "*" # Groups ALL dependencies in a single PR
    assignees:
      - Arlaxia

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      dependencies:
        patterns:
          - "*"
    assignees:
      - Arlaxia
