# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      dependencies:
        patterns:
          - "*" # Groups ALL dependencies in a single PR
    assignees:
      - Arlaxia
    reviewers:
      - perepicornell
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      dependencies:
        patterns:
          - "*"
    assignees:
      - Arlaxia
    reviewers:
      - perepicornell
