# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"
        # Ignore non-LTS Django releases
        # https://www.djangoproject.com/download/#supported-versions
        versions:
          - ">=4.3,<5.2"
    target-branch: "develop"
    # We define a group so as to group all dependabot PRs into one
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      python-dependencies:
        patterns:
          - "*" # Groups ALL dependencies in a single PR
    assignees:
      - Arlaxia

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    # We define a group so as to group all dependabot PRs into one
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      docker-dependencies:
        patterns:
          - "*"
    assignees:
      - Arlaxia
