# Generated by Django 4.0.4 on 2022-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surnames',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='surname'),
        ),
    ]
