# Generated by Django 4.0.4 on 2022-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_data_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
