# Generated by Django 5.1.2 on 2024-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Specifies whether the user has verified their email. You can only access the different sections of the application when you have verified it.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the box is unchecked, the user will not be able to authenticate to access the application. It is usually only disabled when you want to unsubscribe a user but retaining their data.'),
        ),
    ]
