# Don't run on Django migrations
exclude: "/migrations/"
default_stages: ["pre-commit"]

repos:
  # Various file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key

  # Python formatting with black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["src/apps/", "src/conf/"]

  # Python import formatting with isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["src/apps/", "src/conf/"]

  # Python linting with flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["src/"]

  # Poetry checks
  # https://python-poetry.org/docs/pre-commit-hooks/
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock

# Sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
# Taken from https://github.com/cookiecutter/cookiecutter-django
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
