[tool.poetry]
name = "boilerplate_django"
version = "0.1.0"
description = "Plantilla per a nous projectes web amb Django."
authors = ["Codi Cooperatiu <hola@codi.coop>"]
license = "gpl-3.0"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.4"
django-environ = "^0.8.1"
gunicorn = "^20.1.0"
psycopg2-binary = "^2.9.3"
whitenoise = "^6.0.0"
django-maintenance-mode = "^0.16.3"
tox = "^3.25.0"
django-grappelli = "^3.0.3"
django-constance = {extras = ["database"], version = "^2.8.0"}

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
coverage = "^6.3.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
