# Generated by Django 5.1 on 2024-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text_1', models.CharField(help_text='Help field_text_1', max_length=50)),
                ('field_text_2', models.CharField(help_text='Help field_text_2', max_length=100)),
                ('field_email', models.EmailField(help_text='Help field_email', max_length=100, unique=True)),
                ('field_radio', models.CharField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], help_text='Help field_radio', max_length=4)),
                ('field_boolean_checkbox', models.BooleanField(default=False, help_text='Help field_boolean_checkbox')),
                ('field_select_dropdown', models.CharField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_select_dropdown', max_length=4)),
                ('field_password', models.CharField(help_text='Help field_password', max_length=50)),
                ('field_password_confirm', models.CharField(help_text='Help field_password_confirm', max_length=50)),
                ('field_number', models.IntegerField(blank=True, help_text='Help field_number', null=True)),
                ('field_select_checkbox', models.CharField(blank=True, default='OP1', help_text='Help field_select_checkbox', max_length=250)),
            ],
        ),
    ]
