# Generated by Django 5.1.4 on 2024-12-10 17:34

import django.core.validators
import project.storage_backends
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_text_1', models.CharField(blank=True, help_text='Help field_text_1', max_length=50)),
                ('field_text_2', models.CharField(blank=True, help_text='Help field_text_2', max_length=100)),
                ('field_email', models.EmailField(help_text='Help field_email', max_length=100, unique=True)),
                ('field_radio', models.CharField(blank=True, choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_radio', max_length=4)),
                ('field_boolean_checkbox', models.BooleanField(default=False, help_text='Help field_boolean_checkbox')),
                ('field_select_dropdown', models.CharField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_select_dropdown', max_length=4)),
                ('field_password', models.CharField(blank=True, help_text='Help field_password', max_length=50)),
                ('field_password_confirm', models.CharField(blank=True, help_text='Help field_password_confirm', max_length=50)),
                ('field_number', models.IntegerField(blank=True, default=0, help_text='Help field_number')),
                ('field_incremental_number', models.IntegerField(blank=True, default=0, help_text='Help field_incremental_number')),
                ('field_select_checkbox', models.CharField(blank=True, default='OP1', help_text='Help field_select_checkbox', max_length=250)),
                ('field_image', sorl.thumbnail.fields.ImageField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Sorl thumbnail Image field')),
                ('field_file', models.FileField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Generic file field')),
                ('field_time', models.TimeField(blank=True, help_text='Help text for Time field.', null=True, verbose_name='Time field')),
                ('field_date', models.DateField(blank=True, default=None, help_text='Help text for field_date', null=True, verbose_name='Generic date field')),
            ],
        ),
    ]
