# Generated by Django 5.1.2 on 2024-12-04 14:39

import django.core.validators
import project.storage_backends
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='field_file',
            field=models.FileField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image field'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Sorl thumbnail Image field'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_number',
            field=models.IntegerField(blank=True, default=0, help_text='Help field_number'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_radio',
            field=models.CharField(blank=True, choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_radio', max_length=4),
        ),
    ]
