# Generated by Django 5.1.2 on 2024-10-25 13:45

import django.core.validators
import project.storage_backends
import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='field_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
