# Generated by Django 5.1.4 on 2024-12-09 11:13

import project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_data_field_file_alter_data_field_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='field_date',
            field=models.DateField(blank=True, default=None, help_text='Help text for field_date', null=True, verbose_name='Generic date field'),
        ),
        migrations.AddField(
            model_name='data',
            name='field_time',
            field=models.TimeField(blank=True, help_text='Help text for Time field.', null=True, verbose_name='Time field'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_file',
            field=models.FileField(blank=True, default='', storage=project.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Generic file field'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password',
            field=models.CharField(blank=True, help_text='Help field_password', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password_confirm',
            field=models.CharField(blank=True, help_text='Help field_password_confirm', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_text_1',
            field=models.CharField(blank=True, help_text='Help field_text_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_text_2',
            field=models.CharField(blank=True, help_text='Help field_text_2', max_length=100),
        ),
    ]
