# Generated by Django 5.0.3 on 2024-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_data_field_select_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='field_boolean_checkbox',
            field=models.BooleanField(default=False, help_text='Help field_boolean_checkbox'),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_email',
            field=models.EmailField(help_text='Help field_email', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_number',
            field=models.IntegerField(blank=True, help_text='Help field_number', null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password',
            field=models.CharField(help_text='Help field_password', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_password_confirm',
            field=models.CharField(help_text='Help field_password_confirm', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_radio',
            field=models.CharField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], help_text='Help field_radio', max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_select_checkbox',
            field=models.CharField(blank=True, default='OP1', help_text='Help field_select_checkbox', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_select_dropdown',
            field=models.CharField(choices=[('OP1', 'Option 1'), ('OP2', 'Option 2'), ('OP3', 'Option 3')], default='OP1', help_text='Help field_select_dropdown', max_length=4),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_text_1',
            field=models.CharField(help_text='Help field_text_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='field_text_2',
            field=models.CharField(help_text='Help field_text_2', max_length=100),
        ),
    ]
