# Generated by Django 5.1.2 on 2024-12-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra_settings', '0008_auto_20221024_0717'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extra_settings.setting')),
            ],
            bases=('extra_settings.setting',),
        ),
    ]
