x-app: &default-app
  build:
    context: ".."
    dockerfile: ./docker/Dockerfile
    target: "development"
  env_file: "./settings/development.env"
  volumes:
    - "..:/app"
  tty: true
  stop_grace_period: "3s"
  depends_on:
    develop_django_boilerplate_redis:
      condition: service_started
    develop_django_boilerplate_db:
       condition: service_healthy

services:
  develop_django_boilerplate_db:
    image: "postgres:14-bullseye"
    environment:
      POSTGRES_USER: "${DB_USER-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-postgres}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    stop_grace_period: "3s"

  develop_django_boilerplate_app:
    <<: *default-app
    restart: on-failure

  develop_django_boilerplate_celery:
    <<: *default-app
    command: celery -A apps.celery worker --loglevel=INFO
    entrypoint: []

  develop_django_boilerplate_nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d:ro
    ports:
      - 8001:80
    depends_on:
      - develop_django_boilerplate_app
    stop_grace_period: "3s"

  develop_django_boilerplate_redis:
    image: redis
    stop_grace_period: "3s"