version: "3.5"

networks:
  boilerplate-network:
    name: boilerplate-network

services:
  boilerplate-app:
    restart: on-failure
    container_name: boilerplate-app
    build:
      context: ../..
      dockerfile: ./boilerplate_django/docker/Dockerfile
      target: development
    env_file: ./.env
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --reload --threads=10
    ports:
      - "4321:8000"
    volumes:
      - ../src:/srv
      - ../../codi-cooperatiu-internal-tools:/codi-cooperatiu-internal-tools
    depends_on:
      - boilerplate-db
    networks:
      - boilerplate-network

  boilerplate-db:
    container_name: boilerplate-db
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - boilerplate-network

  boilerplate-selenium:
    container_name: boilerplate-selenium
    image: selenium/standalone-chrome:4.16.0
    networks:
      - boilerplate-network
