# Generated by Django 5.0.3 on 2024-07-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'comarca',
                'verbose_name_plural': 'comarques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('name_for_justification', models.CharField(blank=True, default='', max_length=250, verbose_name='nom per la justificació')),
                ('county', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counties_towns.county')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
                'ordering': ['name'],
            },
        ),
    ]
