name: hadolint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: 'docker/Dockerfile'
          failure-threshold: style
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      # Eventually the tests will become more complex and then it
      # should be advisable to move this into a shell script.
      - name: "Build Docker image"
        run: |
          cp docker/settings/settings.env.example docker/settings/development.env
          docker compose -f docker/docker-compose.yml config --quiet
          docker compose -f docker/docker-compose.yml build
          docker compose -f docker/docker-compose.yml up
