name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - './Dockerfile'
  pull_request:
    branches:
      - "*"
    paths:
      - './Dockerfile'
  workflow_dispatch:

concurrency: 
  group: hadolint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: './Dockerfile'
          failure-threshold: style
