name: "CI"

on: 
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Build containers, check formatting and execute tests"
        run: |
          # Django requires static files to be collected in order to run its
          # test suite. That means we need to generate production assets from
          # esbuild. This line ensures NODE_ENV is set to production.
          sed -i "s|export NODE_ENV|#export NODE_ENV|g" .env*

          ./run ci:test
