name: shellcheck

on:
  push:
    branches:
      - main
    paths:
      - 'bin/*.sh'
  pull_request:
    paths:
      - 'bin/*.sh'
  workflow_dispatch:

concurrency:
  group: shellcheck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: --shell bash
        with:
          severity: style
          check_together: 'yes'
